star_index: "/work/mc394/star_index/GRCm38"
annotation: "/work/mc394/genomes/annotation/wgencode.vM17.primary_assembly.annotation.gtf"
count_filename: "generic.counts"
paired: "false"
# Strandedness of reads ("none", "forward", or "reverse")
stranded: "none"